package chain

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"time"

	"github.com/btcsuite/btcd/chaincfg"
)

// DASH uses the same block wire format as BTC (80-byte headers, same tx format).
// X11 PoW is not validated in the contract, so the BTC parser works.
// DASH uses P2SH instead of native SegWit on mainnet, but the mapping contract
// uses P2WSH internally so we keep the same address generator.
//
// Address version bytes must match dash-mapping-contract's init.go
// (dashMainNetParams / dashTestNetParams) — otherwise deposit addresses
// generated by the bot won't round-trip with addresses validated by the
// contract (different Bech32 HRP → different P2WSH encoding).

func dashMainNetParams() *chaincfg.Params {
	p := chaincfg.MainNetParams
	p.PubKeyHashAddrID = 0x4c // 'X' prefix
	p.ScriptHashAddrID = 0x10 // '7' prefix
	p.Bech32HRPSegwit = "dash"
	return &p
}

func dashTestNetParams() *chaincfg.Params {
	p := chaincfg.TestNet3Params
	p.PubKeyHashAddrID = 0x8c // 'y' prefix
	p.ScriptHashAddrID = 0x13 // '8'/'9' prefix
	p.Bech32HRPSegwit = "tdash"
	return &p
}

// dashRPCEndpoint resolves a dashd JSON-RPC endpoint from environment variables,
// falling back to the default `vsc-dashd-*` container the magi testnet stack
// runs. Set DASHD_TESTNET_RPC_URL / DASHD_MAINNET_RPC_URL to point elsewhere.
func dashRPCEndpoint(envPrefix, defaultURL, defaultUser, defaultPass string) (url, user, pass string) {
	url = os.Getenv(envPrefix + "_RPC_URL")
	if url == "" {
		url = defaultURL
	}
	user = os.Getenv(envPrefix + "_RPC_USER")
	if user == "" {
		user = defaultUser
	}
	pass = os.Getenv(envPrefix + "_RPC_PASS")
	if pass == "" {
		pass = defaultPass
	}
	return
}

// dashAttachZMQ optionally wires a ZMQ pub-sub subscriber onto the dashd RPC
// client. Controlled by `DASHD_{NETWORK}_ZMQ_URL` (e.g.
// "tcp://vsc-dashd-testnet:28332"). Empty value → no ZMQ, client stays in
// poll-only mode. Failures are logged and swallowed so a bad ZMQ config
// doesn't take the whole bot down.
func dashAttachZMQ(envPrefix string, rpc *DashdRPCClient, params *chaincfg.Params) {
	endpoint := os.Getenv(envPrefix + "_ZMQ_URL")
	if endpoint == "" {
		return
	}
	zmq, err := NewDashdZMQSubscriber(context.Background(), endpoint)
	if err != nil {
		slog.Warn("dashd zmq: subscriber init failed; continuing in poll-only mode",
			"endpoint", endpoint, "err", err)
		return
	}
	rpc.AttachZMQ(zmq, params)
}

func NewDASHMainnet(httpClient *http.Client) *ChainConfig {
	params := dashMainNetParams()
	url, user, pass := dashRPCEndpoint(
		"DASHD_MAINNET",
		"http://vsc-dashd-mainnet:9998",
		"vsc-node-user", "vsc-node-pass",
	)
	rpc := NewDashdRPCClient(httpClient, url, user, pass)
	dashAttachZMQ("DASHD_MAINNET", rpc, params)
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               rpc,
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &DashAddressGenerator{Params: params, BackupCSVBlocks: 17280},
		BlockInterval:        150 * time.Second, // 2.5 min blocks
		SleepInterval:        time.Minute,
		DropHeightDiff:       17280,
		HistoricalTxLookback: 4032, // ~7 days at 2.5 min
		ChainParams:          params,
		DefaultDbName:        "dash-mapping-bot",
	}
}

func NewDASHTestnet(httpClient *http.Client) *ChainConfig {
	params := dashTestNetParams()
	url, user, pass := dashRPCEndpoint(
		"DASHD_TESTNET",
		"http://vsc-dashd-testnet:19998",
		"vsc-node-user", "vsc-node-pass",
	)
	rpc := NewDashdRPCClient(httpClient, url, user, pass)
	dashAttachZMQ("DASHD_TESTNET", rpc, params)
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               rpc,
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &DashAddressGenerator{Params: params, BackupCSVBlocks: 2},
		BlockInterval:        150 * time.Second,
		SleepInterval:        10 * time.Second,
		DropHeightDiff:       17280,
		HistoricalTxLookback: 4032,
		ChainParams:          params,
		DefaultDbName:        "dash-mapping-bot-testnet",
	}
}

// dashRegtestParams applies the Dash regtest address-version overrides on
// top of btcsuite's RegressionNetParams. Matches
// dash-mapping-contract/contract/mapping/init.go::dashRegTestParams so the
// bot derives the same P2SH addresses the contract validates.
func dashRegtestParams() *chaincfg.Params {
	p := chaincfg.RegressionNetParams
	p.PubKeyHashAddrID = 0x8c
	p.ScriptHashAddrID = 0x13
	return &p
}

// NewDASHRegtest mirrors NewBTCRegtest but uses the Dash-overridden regtest
// params (matching the contract's regtest network). Deposit addresses come
// out as P2SH base58 (prefix 8/9), which Dash Core actually accepts.
func NewDASHRegtest(httpClient *http.Client) *ChainConfig {
	params := dashRegtestParams()
	url, user, pass := dashRPCEndpoint(
		"DASHD_REGTEST",
		"http://localhost:19898",
		"vsc-node-user", "vsc-node-pass",
	)
	rpc := NewDashdRPCClient(httpClient, url, user, pass)
	dashAttachZMQ("DASHD_REGTEST", rpc, params)
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               rpc,
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &DashAddressGenerator{Params: params, BackupCSVBlocks: 2},
		BlockInterval:        time.Second,
		SleepInterval:        time.Second,
		DropHeightDiff:       100,
		HistoricalTxLookback: 100,
		ChainParams:          params,
		DefaultDbName:        "dash-mapping-bot-regtest",
	}
}
